<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    /* dompdf has weak CSS support (no flexbox/grid) — table-based layout is the
       reliable, standard approach for PDF generation with this library. Colors
       match resources/css/app.css's theme tokens, hardcoded here since dompdf
       can't read our Tailwind build. */
    body { font-family: DejaVu Sans, sans-serif; color: #132A1E; font-size: 12px; }
    .header-table { width: 100%; margin-bottom: 24px; }
    .brand { font-size: 16px; font-weight: bold; color: #173B28; }
    .muted { color: #77897E; }
    .status {
        display: inline-block; padding: 4px 10px; border-radius: 12px;
        font-size: 10px; font-weight: bold; text-transform: uppercase;
        background: #DDF3E3; color: #3FAE6A;
    }
    table.items { width: 100%; border-collapse: collapse; margin-top: 16px; }
    table.items th {
        text-align: left; font-size: 9px; text-transform: uppercase; color: #77897E;
        border-bottom: 1px solid #E9F1EC; padding: 6px 0;
    }
    table.items td { padding: 8px 0; border-bottom: 1px solid #E9F1EC; }
    .text-right { text-align: right; }
    .totals-table { width: 240px; margin-left: auto; margin-top: 16px; }
    .totals-table td { padding: 4px 0; font-size: 12px; }
    .grand-total { font-size: 15px; font-weight: bold; border-top: 1px solid #E9F1EC; padding-top: 8px; }
    .footer { margin-top: 40px; font-size: 10px; color: #9BAAA1; text-align: center; }
</style>
</head>
<body>
    <table class="header-table">
        <tr>
            <td>
                <div class="brand">{{ $tenantName }}</div>
            </td>
            <td class="text-right">
                <span class="status">{{ $invoice->status }}</span>
            </td>
        </tr>
    </table>

    <table class="header-table">
        <tr>
            <td>
                <div class="muted">Invoice</div>
                <div style="font-size:14px; font-weight:bold;">{{ $invoice->invoice_number }}</div>
            </td>
            <td>
                <div class="muted">Billed to</div>
                <div style="font-weight:bold;">{{ $invoice->client->name }}</div>
                @if($invoice->client->email)
                    <div class="muted">{{ $invoice->client->email }}</div>
                @endif
            </td>
            <td class="text-right">
                <div class="muted">Issued: {{ $invoice->issue_date->format('M d, Y') }}</div>
                <div class="muted">Due: {{ $invoice->due_date->format('M d, Y') }}</div>
            </td>
        </tr>
    </table>

    <table class="items">
        <thead>
            <tr>
                <th>Description</th>
                <th class="text-right">Qty</th>
                <th class="text-right">Unit price</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoice->items as $item)
                <tr>
                    <td>{{ $item->description }}</td>
                    <td class="text-right">{{ $item->quantity }}</td>
                    <td class="text-right">{{ $item->unit_price }}</td>
                    <td class="text-right">{{ $item->line_total }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <table class="totals-table">
        <tr><td class="muted">Subtotal</td><td class="text-right">{{ $invoice->subtotal }}</td></tr>
        <tr><td class="muted">Tax</td><td class="text-right">{{ $invoice->tax_amount }}</td></tr>
        <tr><td class="muted">Discount</td><td class="text-right">-{{ $invoice->discount }}</td></tr>
        <tr class="grand-total"><td>Total due</td><td class="text-right">{{ $invoice->currency }} {{ $invoice->total }}</td></tr>
    </table>

    @if($invoice->notes)
        <div style="margin-top:24px; padding-top:12px; border-top:1px solid #E9F1EC;" class="muted">
            {{ $invoice->notes }}
        </div>
    @endif

    <div class="footer">Generated by PlusicInvoice on {{ now()->format('M d, Y') }}</div>
</body>
</html>
